masterDeckName: test_deck
modelName: test_model
fields:
  - question
  - answer
  - picture
singleDeck: false
csvDelimiter: ";"
webserver:
  enabled: true
  port: 1233
  listenAddress: 0.0.0.0
urlCheck:
  enabled: true
  timeout: 1
