name: Publish Docker image

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '*.md'
      - 'anki/**'
  pull_request:
    branches:
      - 'main'
    paths-ignore:
      - '*.md'
      - 'anki/**'

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Repo checkout
        uses: actions/checkout@v4

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: thisisnttheway
          password: ${{ secrets.DOCKER_HUB_SECRET }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: thisisnttheway/anki-deck-compiler
          tags: |
            type=ref,event=tag
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
            type=ref,event=branch,enable=${{ github.ref != format('refs/heads/{0}', 'main') }}
            type=sha

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
